datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.prometheus:9090
      - name: loki
        type: loki
        url: http://loki.loki:3100

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'default'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    loki:
      gnetId: 13186
      revision: 1
      datasource: Loki
    loki:
      gnetId: 6671
      revision: 2
      datasource: Prometheus
