image:
  repository: ghcr.io/hanssenkai/go-api-observability-test
  tag: latest
ports:
- name: http
  containerPort: 8080
  protocol: TCP
envFrom:
  - secretRef:
      name: db-app
ingress:
  enabled: false
