image:
  repository: ghcr.io/hanssenkai/go-api-observability-test
  tag: latest
  pullSecrets:
  - imagepull
ports:
- name: http
  containerPort: 8080
  protocol: TCP
envVarsSecret: "db-app"
ingress:
  enabled: false
