name: Pull request review app

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'  # Specify your Go version

    - name: Run tests
      run: |
        go test

    - uses: ko-build/setup-ko@v0.6

    - run: |
        PR_TAG="pr-${{ github.event.pull_request.number }}-${{ github.sha }}"
        ko build  --tags $PR_TAG
